version: "2"

services:
  hlds:
    image: hitman99/hlds
    environment: 
      - START_MAP=bounce 
      - ADMIN_STEAM=0:1:67012979
      - SERVER_NAME=vfrc2's cs 16 server"
    ports:
      - 27020:27015/udp